version: '3.8'

services:
  web:
    build: .
    container_name: js-fastapi-monitoring
    volumes:
      - .:/code
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
